version: "3.7"

volumes: 
    data:
    configdb:

services:
    client:
        image: node
        working_dir: /app/client
        volumes: 
            - ./client:/app/client
        command: npm start
        environment: 
            - NODE_ENV=developement
            - PORT=3000
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true
        depends_on: 
            - server

    db:
        image: mongo:latest
        container_name: mongo
        volumes: 
            - ./db_init.js:/docker-entrypoint-initdb.d/db_init.js
            - "data:/data/db"
            - "configdb:/data/configdb"
        environment: 
            - MONGO_INITDB_DATABASE=lighthouse
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        ports:
            - "27017:27017"

    server:
        image: node
        working_dir: /app/server
        volumes:
            - ./server:/app/server
        command: npm start
        environment: 
            - NODE_ENV=developement
            - PORT=5000
        ports:
            - "5000:5000"
        stdin_open: true
        depends_on: 
            - db
        links:
            - db:db

